name: 'Run CI'
description: 'Run linting and testing tasks'

runs:
    using: 'composite'
    steps:
        - name: Install dependencies
          shell: bash
          run: pnpm install --frozen-lockfile

        - name: Run linting jobs
          shell: bash
          run: |
              pnpm run prettier
              pnpm run lint
              pnpm run markdownlint

        - name: Run tests with coverage
          shell: bash
          run: pnpm run test:coverage

        - name: Build
          shell: bash
          run: pnpm build
