name: 'Setup Environment'
description: 'Setup Environment for Public GitHub'
inputs:
    node-version:
        description: 'Node.js version to setup'
        required: true
        default: '24'
    python-version:
        description: 'Python version to setup'
        required: true
        default: '3.13'
    java-version:
        description: 'Java version to setup'
        required: true
        default: '11'
    java-distribution:
        description: 'Java distribution to use'
        required: false
        default: 'temurin'
runs:
    using: 'composite'
    steps:
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: ${{ inputs.node-version }}
              registry-url: 'https://registry.npmjs.org/'

        - name: Setup pnpm
          uses: pnpm/action-setup@v4

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
              python-version: ${{ inputs.python-version }}

        - name: Install uv
          uses: astral-sh/setup-uv@v4

        - name: Install just
          uses: extractions/setup-just@v2

        - name: Setup Java
          uses: actions/setup-java@v4
          with:
              java-version: ${{ inputs.java-version }}
              distribution: ${{ inputs.java-distribution }}
